### ISSUE TITLE
Small todo list

### ISSUE THREAD

**Issue by cm4ker** [cm4ker/platform#44]
- [x] add 'remove(item)' method
- [x]  link add collection
- [x]  add 'reload' method to the collection()
